---
title: "Análisis de autocorrelación espacial"
author: 
  -"Juan José Galeano Arenas"
  -"Simón Pedro Galeano Muñoz"
  -"Germán Alonso Patiño Hurtado"
date: 10/05/2022
output: 
  html_document:
    toc: true
    theme: paper
    code_folding: show
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, fig.align = "center",
                      message = F, results = F)
library(kableExtra)
library(knitr)
library(geoR)
library(readxl)
library(vegan)
library(raster)
library(spatstat)
```

# Contextualización

```{r echo=F}
# Bases de datos necesarias
datos_cools <- readRDS("datos.Rds")
```

# Datos

Se tienen datos del riesgo de contagio de malaria 

## Análisis descriptivo y prueba de autocorrelación espacial

```{r}
x_obs <- c(min(datos_cools$LON), max(datos_cools$LON))
y_obs <- c(min(datos_cools$LAT), max(datos_cools$LAT))
obs_window <- owin(x_obs, y_obs)
```


# Interpolación IDW

```{r}
ppp_temp <- ppp(datos_cools$LON, datos_cools$LAT,
                 marks = datos_cools$Temperatura, window = obs_window)

idw_temp <- idw(ppp_temp, power = 0.05, at = "pixels")

plot(idw_temp,
     col = heat.colors(20), 
     main = "Interpolación IDW para la temperatura promedio") 
```

## MSE

# Cross - Validation

```{r}
par(mfrow=c(2,2))
plot(idw(ppp_temp, power=0.001, at="pixels"),
     col=heat.colors(20), main="power = 0.001") 

plot(idw(ppp_temp, power=0.01, at="pixels"),
     col=heat.colors(20), main="power = 0.01")

plot(idw(ppp_temp, power=0.1, at="pixels"),
     col=heat.colors(20), main="power = 0.1")

plot(idw(ppp_temp, power=10, at="pixels"),
     col=heat.colors(20), main="power = 10") 
```

## Buscando la potencia óptima

```{r}
powers <- seq(0.001, 10, 0.01)
mse_result <- NULL
for(power in powers){
  CV_idw <- idw(ppp_temp, power=power, at="points")
  mse_result <- c(mse_result,
                  Metrics::mse(ppp_temp$marks, CV_idw))
}
optimal_power <- powers[which.min(mse_result)]
optimal_power

plot(powers, mse_result)
powers[which.min(mse_result)]
```

```{r}
idw_temp_optimo <- idw(ppp_temp, power = 1.411, at = "pixels")

plot(idw_temp_optimo,
     col = heat.colors(20), 
     main = "Interpolated spatial variation in risk of malaria based on IDW method \n (Power = 0.05)") 

```





