---
header-includes:
- \usepackage{longtable}
- \usepackage[utf8]{inputenc}
- \usepackage[spanish]{babel}\decimalpoint
- \setlength{\parindent}{1.25cm}
- \usepackage{amsmath}
- \usepackage{xcolor}
- \usepackage{cancel}
- \usepackage{array}
- \usepackage{float}
- \usepackage{multirow}
output:
  pdf_document: 
    number_sections: no
fontsize: 12pt
papersize: letter
geometry: margin = 1in
language: "es"
editor_options: 
  markdown: 
    wrap: 72
---
```{=tex}
\input{titlepage}
\newpage
\thispagestyle{empty}
\tableofcontents
\newpage
```

```{=tex}
\pagestyle{myheadings}
\setcounter{page}{3}
```

\section{Capitulo I: Computación cuántica, una evolución inminente}

Alcides Montoya Cañola es docente de la Universidad Nacional de Colombia 17
años, presenta una fotografía tomada en el 2019 de un computador cuántico
donde nos enseña el núcleo y sus partes el cual esta funcionando y es monitoreado por Google, a partir de estas partes se hace una transformación para que sea un compilador y programar en un lenguaje conocido para nosotros. En 2018 Google hace publico un trabajo donde se menciona la supremacía cuántica, donde se muestra un algoritmo cuántico donde dice que para un computador clásico se puede demorar cientos de años y este lo resolvió en un par de días. Una de las desventajas del computador cuántico es que tiene que estar en una temperatura de 0 °C absoluto lo cual no es posible en cualquier lado, tienen que estár en laboratorios para monitorear las condiciones de este, D-Wave está apostando por que este se pueda trabajar en temperatura ambiente. 

Los algoritmos cuánticos:  Short, HHL, SDP, Trotter-based algoritmos con velocidad potencial exponencial. QAE, VQE, DDQCL, QAQA, QEPT y Grover search con una velocidad potencial polinomial.

Algunos casos de uso son la química, algoritmos, comunicación y de interés para los estadísticos o científicos de datos como el machine learning y simulación, lo que haría procesos mucho más rápidos.  
Un posible riesgo de la computación cuántica es que a manos de hackers expertos puede dar a vulnerar claves, para este problema se está trabajando en criptografía post cuántica.

Dada la naturaleza del trabajo al se enfrenta un estadístico, científico de datos o afín, el tema de computación cuántica resulta de particular interés porque esta se presenta como una evolución al sistema de computación clásica al cual ya se está acostumbrado. El sistema clásico ha logrado que la humanidad avance gracias a la variedad de aplicaciones que ha tenido en múltiples áreas, sin embargo, esta también se puede ver limitada en problemas más complejos, por ejemplo, cuando se quiere ajustar algún modelo de machine learning y este tarda horas o incluso días en realizar el ajuste, por lo que nace de manera natural la pregunta de cómo solucionar esta problemática. La computación cuántica expande el margen de posibilidades puesto que además de solucionar problemas de computación clásica de manera más efectiva, también podría dar entrada a la solución de otros tipos de problemas aún más complejos. 

Aunque la potencia de la computación cuántica se ve en una escala superior, esta se encuentra en pleno desarrollo y la existencia de algunas desventajas notables como, por ejemplo, la temperatura del equipo implica que todavía deban pasar varios años hasta que este pueda ser un estándar mundial como ya lo es la computación clásica, no obstante, dado que el estadístico necesita constantemente el poder de la computación en el día a día, resulta muy importante conocer como avanza esta nueva tecnología que, eventualmente, podría ser la evolución del enfoque que ya se conoce logrando cosas que antes solo eran producto de la imaginación.


\section{Capítulo II: la estadística espacial llegó para quedarse}

La estadística espacial no es solo la inclusión de un contexto del espacio y del tiempo, es una propuesta para detectar lo no antes visto y potenciar el análisis a través de lo ya existente.

Desde siempre la estadística ha sido la mejor amiga de cualquier ciencia o área en general, pues es el medio traductor entre la manifestación de la realidad a través de registros que resultan de interés y el verdadero significado en lo oculto de dicha manifestación, sin embargo esta tarea de traducir ha requerido de un esfuerzo colectivo para desarrollar metodologías que permitan entablar una conversación directa con los datos para extraer de ellos información que permita tomar decisiones, llegar a conclusiones, predecir, plantear nuevas hipótesis, entre otras. Para esto, pruebas de hipótesis, modelos aditivos, mixtos, jerárquicos, propuestas que conllevan a la actualización de probabilidades con base en los datos han sido ingeniosamente ideadas, sin embargo el mundo moderno avanza a pasos agigantados y las formas en las que se presentan los datos han evolucionado junto con el globo, por lo que a pesar de la alta fiabilidad de los métodos estadísticos clásicos, es necesario avanzar y modernizarse, de allí la necesidad del surgimiento de áreas novedosas como la estadística espacial.

Pero ¿por qué la estadística espacial? A pesar de que la respuesta puede ser tema para un desarrollo entero, en este caso basta con mencionar que es de suma importancia traer a colación que los fenómenos se extienden por tiempo y espacio, si bien son elementos que quizás no es muy frecuente tenerlos en cuenta a la hora de realizar análisis de datos, el mero hecho de considerarlos enriquece naturalmente el análisis para no solo analizar el registro crudo e intentar convertilo en información de valor, si no que para contextualizar según el lugar y la época, para intentar observar como esa conjunción de tiempo y espacio hacen de la estadística espacial la herramienta adecuada para analizar datos modernos, puesto que el sitio y el tiempo exacto de recopilación de los datos también tienen algo por decir y gracias a esto es posible llevar a cabo tareas como estimar el riesgo de una enfermedad y cuantificarlo por región y por época del año, detección temprana de brotes, considerar factores de riesgo y ambientales que son propios de los territorios, entre otros.

En conclusión, la estadística espacial es un área que al gozar de una extensión de elementos clásicos, incorporación de métodos altamente eficientes como los bayesianos y de la consideración de los efectos espacio y tiempo sobre los datos, ha llegado para quedarse, potenciar el análisis y llevar al analista a un terreno con un panorama más claro donde pueda observar aquello que sin estadística espacial hubiera ignorado.
